In [1]:
# 1. Import necessary libraries: numpy, sklearn.datasets, sklearn.neighbors, sklearn.tree, and sklearn.svm.
# Load the Iris dataset using datasets.load_iris().
from sklearn import datasets
iris= datasets.load_iris()

In [3]:
# 2. Split the dataset into training and testing sets. Use 80% of the samples for training and 20% for testing. 
import numpy as np
from sklearn import datasets
np.random.seed(0)
iris = datasets.load_iris()
x = iris.data #predictors (features) use x to refer to independent features
y = iris.target #Outcome to be predicted use y to refer to the dependent features - related to the target 

# permutation is one method to shuffle data - give the method the length (iris.data) 150 
i = np.random.permutation(len(iris.data)) # use this to shuffle the records - dont want them sorted
print(i)

# Here is where the data is split for training and testing. 120 = 80% and 30 = 20% 
x_train = x[i[:-30]]#120 (all but the last 30) this is -30 from the end - from 150 - will have 120 values and 4 columns(features)
y_train = y[i[:-30]]#120 (outcome) 1 column - showing which flower 0, 1 or 2 
x_test = x[i[-30:]]#the last 30 records with  4 columns(features)
y_test = y[i[-30:]]#the last 30 records with 1 

[114  62  33 107   7 100  40  86  76  71 134  51  73  54  63  37  78  90
  45  16 121  66  24   8 126  22  44  97  93  26 137  84  27 127 132  59
  18  83  61  92 112   2 141  43  10  60 116 144 119 108  69 135  56  80
 123 133 106 146  50 147  85  30 101  94  64  89  91 125  48  13 111  95
  20  15  52   3 149  98   6  68 109  96  12 102 120 104 128  46  11 110
 124  41 148   1 113 139  42   4 129  17  38   5  53 143 105   0  34  28
  55  75  35  23  74  31 118  57 131  65  32 138  14 122  19  29 130  49
 136  99  82  79 115 145  72  77  25  81 140 142  39  58  88  70  87  36
  21   9 103  67 117  47]


In [5]:
# 3.1 Implement and train the following classifiers: k-Nearest Neighbors (KNN)
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
# training the model
knn.fit(x_train,y_train)

KNeighborsClassifier()

In [7]:
# Make predictions on the testing set for each classifier
knn.predict(x_test) #predicted y

array([0, 2, 0, 0, 2, 0, 2, 1, 1, 1, 2, 2, 2, 1, 0, 1, 2, 2, 0, 1, 1, 2,
       1, 0, 0, 0, 2, 1, 2, 0])

In [9]:
# This will tell you the actual class of the 30 flowers 
y_test #actual y

array([0, 2, 0, 0, 2, 0, 2, 1, 1, 1, 2, 2, 1, 1, 0, 1, 2, 2, 0, 1, 1, 1,
       1, 0, 0, 0, 2, 1, 2, 0])

In [11]:
# The KNN model predicted y 28 out of 30 times accurately 

# Evaluate the performance of each classifier using the following metrics; Accuracy, F1-score, Precision, Recall
# Print out the evaluation metrics for each classifier 

from sklearn.neighbors import KNeighborsClassifier
# name assigned to classifier - knn
knn = KNeighborsClassifier()
knn.fit(x_train,y_train)
pred_y=knn.predict(x_test)

from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score

# when you have target variables greater than 2 make sure to use average='micro'
# python will create 3 machine learning models when there are greater than 2 targer variables (classes)
print ("f1:" + str(f1_score(pred_y, y_test,average='micro')))
print ("accuracy:" + str(accuracy_score(pred_y, y_test)))
print ("precision:" + str(precision_score(pred_y, y_test,average='micro')))
print ("recall:" + str(recall_score(pred_y, y_test,average='micro')))

f1:0.9333333333333333
accuracy:0.9333333333333333
precision:0.9333333333333333
recall:0.9333333333333333


In [17]:
# 3.2 Decision Tree
from sklearn import tree
clf = tree.DecisionTreeClassifier()
# train model
clf = clf.fit(x_train, y_train)
# make prediction
pred_y = clf.predict(x_test)#pred_y=[1,2,2,1,..........,2]
# evaluate the prediction results

from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score

print ("f1:" + str(f1_score(pred_y, y_test,average='micro')))
print ("accuracy:" + str(accuracy_score(pred_y, y_test)))
print ("precision:" + str(precision_score(pred_y, y_test,average='micro')))
print ("recall:" + str(recall_score(pred_y, y_test,average='micro')))

f1:0.9333333333333333
accuracy:0.9333333333333333
precision:0.9333333333333333
recall:0.9333333333333333


In [23]:
#use library sklearn - most common machine learning library in python 
from sklearn import tree
# clf is the name I assigned for classifier - create the model 
clf = tree.DecisionTreeClassifier()
# train/build model
clf = clf.fit(x_train, y_train)
# make prediction - use the method predict - give the model only the x_test
pred_y = clf.predict(x_test) 
# evaluate the prediction results - model will give the y_test
from sklearn.metrics import classification_report
for line in classification_report(y_test, pred_y).split("\n"):
    print (line)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      0.82      0.90        11
           2       0.82      1.00      0.90         9

    accuracy                           0.93        30
   macro avg       0.94      0.94      0.93        30
weighted avg       0.95      0.93      0.93        30



In [25]:
clf.predict(x_test)

array([0, 2, 0, 0, 2, 0, 2, 1, 1, 1, 2, 2, 1, 2, 0, 1, 2, 2, 0, 1, 1, 2,
       1, 0, 0, 0, 2, 1, 2, 0])

In [27]:
y_test

array([0, 2, 0, 0, 2, 0, 2, 1, 1, 1, 2, 2, 1, 1, 0, 1, 2, 2, 0, 1, 1, 1,
       1, 0, 0, 0, 2, 1, 2, 0])

In [ ]:
# the Decision tree model scored just about the same as the K Neighbors model having predicted 28 of the 30 flowers accurately

In [29]:
# 3.3 Support Vector Machine (SVM)
from sklearn import svm
svc = svm.SVC().fit(x_train,y_train)
pred_y = svc.predict(x_test)

print ("f1:" + str(f1_score(pred_y, y_test,average='micro')))
print ("accuracy:" + str(accuracy_score(pred_y, y_test)))
print ("precision:" + str(precision_score(pred_y, y_test,average='micro')))
print ("recall:" + str(recall_score(pred_y, y_test,average='micro')))


f1:0.9333333333333333
accuracy:0.9333333333333333
precision:0.9333333333333333
recall:0.9333333333333333


In [31]:
svc.predict(x_test)

array([0, 2, 0, 0, 2, 0, 2, 1, 1, 1, 2, 2, 2, 2, 0, 1, 2, 2, 0, 1, 1, 1,
       1, 0, 0, 0, 2, 1, 2, 0])

In [33]:
y_test

array([0, 2, 0, 0, 2, 0, 2, 1, 1, 1, 2, 2, 1, 1, 0, 1, 2, 2, 0, 1, 1, 1,
       1, 0, 0, 0, 2, 1, 2, 0])

In [ ]:
# The SVM model performed just as well as the Decision Tree and K Neighbors models. Predicting 28 out of the 30 flowers accurately 
# For this iris dataset each of these models would be very helpful all theree models scored above .90 on all metrics which is a excellent score 